/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class Clock extends javax.swing.JFrame {

    private final Controller controller = Controller.getInstance();
    
    private String nome = JOptionPane.showInputDialog(null, "Nome da Máquina");
    private String hora = JOptionPane.showInputDialog(null, "Digite a hora");
    private String drift = JOptionPane.showInputDialog(null, "Digite o drift desejado");

    /**
     * Creates new form Clock
     */
    public Clock() {
        initComponents();
        clock.setText(hora);
        iniciarContagem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TimeSynchronizer");
        setAutoRequestFocus(false);
        setResizable(false);

        clock.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clock().setVisible(true);
            }
        });

    }

    public void iniciarContagem() {

        new Thread() {
            @Override
            public void run() {

                String[] inf = hora.split(":");

                int hora = Integer.parseInt(inf[0]);
                int min = Integer.parseInt(inf[1]);
                int seg = Integer.parseInt(inf[2]);
                
                double drift2 = Double.parseDouble(drift);

                while (true) {

                    try {
                        long novo = (long) (1000*drift2);
                        
                        Thread.sleep(novo);
                        seg = seg + 1;

                        if (seg > 59) {
                            seg = 0;
                            min = min + 1;
                            if (min > 59) {
                                min = 0;
                                hora = hora + 1;
                                if (hora > 23) {
                                    hora = 0;
                                }
                            }
                        }
                        
                        controller.enviarHora(hora, min, seg);

                        String hr = hora <= 9 ? "0" + hora : hora + "";
                        String min2 = min <= 9 ? "0" + min : min + "";
                        String seg2 = seg <= 9 ? "0" + seg : seg + "";

                        setLabel(hr + ":" + min2 + ":" + seg2);
                        
                        if (controller.getAtualizarHora()){
                            seg = controller.getSeg();
                            min = controller.getMin();
                            hora = controller.getHora();
                            controller.setAtualizarHora(false);
//                            controller.setHora(0);
//                            controller.setMin(0);
//                            controller.setSeg(0);
                            
                            hr = hora <= 9 ? "0" + hora : hora + "";
                            min2 = min <= 9 ? "0" + min : min + "";
                            seg2 = seg <= 9 ? "0" + seg : seg + "";
                            setLabel(hr + ":" + min2 + ":" + seg2);
                            
                        }
                        
                        
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }

                }
            }
        }.start();
    }

    private void setLabel(String texto) {
        clock.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    // End of variables declaration//GEN-END:variables
}
